# PostgreSQL. Versions 9.3 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: utf-8

development:
  <<: *default
  database: kodep

test:
  <<: *default
  database: kodep
#
production:
  <<: *default
  host: movie-db
  database: kodep
  username: kodep
  password: kodep
  port: 4000
  pool: 5
